using BaseApp.Common;
using BaseApp.Common.Utils;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BaseApp.Data.ProjectMigration.Migrations
{
    /// <inheritdoc />
    public partial class fillUserAndRolesAndCountries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(string.Format(RolesInsertSqlTemplate, 1, Constants.Roles.Admin));
            migrationBuilder.Sql(string.Format(RolesInsertSqlTemplate, 2, Constants.Roles.User));
            migrationBuilder.Sql(string.Format(AdminUserInsertSqlTemplate, PasswordHash.HashPassword("1111111")));

            migrationBuilder.Sql(CountryInsertSql);
            migrationBuilder.Sql(StateInsertSql);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(" DELETE FROM [dbo].[State] ");
            migrationBuilder.Sql(" DELETE FROM [dbo].[Country] ");
        }

        private const string RolesInsertSqlTemplate = @" insert into dbo.[Role] (Id, [Name] ) values ({0}, '{1}') ";

        private const string AdminUserInsertSqlTemplate = @" 
insert into dbo.[User] ([Login], [Password], FirstName, LastName, Email, CreatedDate, UpdatedDate)
values ('admin', '{0}', 'Admin', 'User', 'admin@example.com', GETDATE(), GETDATE())

insert into UserRole (UserId, RoleId)
values (SCOPE_IDENTITY(), 1)";


        private const string CountryInsertSql = @"INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (1, N'Andorra', 20, N'AD', N'AND', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (2, N'United Arab Emirates', 784, N'AE', N'ARE', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (3, N'Afghanistan', 4, N'AF', N'AFG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (4, N'Antigua and Barbuda', 28, N'AG', N'ATG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (5, N'Anguilla', 660, N'AI', N'AIA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (6, N'Albania', 8, N'AL', N'ALB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (7, N'Armenia', 51, N'AM', N'ARM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (8, N'Netherlands Antilles', 530, N'AN', N'ANT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (9, N'Angola', 24, N'AO', N'AGO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (10, N'Antarctica', NULL, N'AQ', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (11, N'Argentina', 32, N'AR', N'ARG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (12, N'American Samoa', 16, N'AS', N'ASM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (13, N'Austria', 40, N'AT', N'AUT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (14, N'Australia', 36, N'AU', N'AUS', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (15, N'Aruba', 533, N'AW', N'ABW', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (16, N'Azerbaijan', 31, N'AZ', N'AZE', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (17, N'Bosnia and Herzegovina', 70, N'BA', N'BIH', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (18, N'Barbados', 52, N'BB', N'BRB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (19, N'Bangladesh', 50, N'BD', N'BGD', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (20, N'Belgium', 56, N'BE', N'BEL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (21, N'Burkina Faso', 854, N'BF', N'BFA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (22, N'Bulgaria', 100, N'BG', N'BGR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (23, N'Bahrain', 48, N'BH', N'BHR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (24, N'Burundi', 108, N'BI', N'BDI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (25, N'Benin', 204, N'BJ', N'BEN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (26, N'Bermuda', 60, N'BM', N'BMU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (27, N'Brunei Darussalam', 96, N'BN', N'BRN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (28, N'Bolivia', 68, N'BO', N'BOL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (29, N'Brazil', 76, N'BR', N'BRA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (30, N'Bahamas', 44, N'BS', N'BHS', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (31, N'Bhutan', 64, N'BT', N'BTN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (32, N'Bouvet Island', NULL, N'BV', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (33, N'Botswana', 72, N'BW', N'BWA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (34, N'Belarus', 112, N'BY', N'BLR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (35, N'Belize', 84, N'BZ', N'BLZ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (36, N'Canada', 124, N'CA', N'CAN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (37, N'Cocos (Keeling) Islands', NULL, N'CC', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (38, N'Congo, the Democratic Republic of the', 180, N'CD', N'COD', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (39, N'Central African Republic', 140, N'CF', N'CAF', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (40, N'Congo', 178, N'CG', N'COG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (41, N'Switzerland', 756, N'CH', N'CHE', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (42, N'Cote D''Ivoire', 384, N'CI', N'CIV', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (43, N'Cook Islands', 184, N'CK', N'COK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (44, N'Chile', 152, N'CL', N'CHL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (45, N'Cameroon', 120, N'CM', N'CMR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (46, N'China', 156, N'CN', N'CHN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (47, N'Colombia', 170, N'CO', N'COL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (48, N'Costa Rica', 188, N'CR', N'CRI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (49, N'Serbia and Montenegro', NULL, N'CS', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (50, N'Cuba', 192, N'CU', N'CUB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (51, N'Cape Verde', 132, N'CV', N'CPV', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (52, N'Christmas Island', NULL, N'CX', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (53, N'Cyprus', 196, N'CY', N'CYP', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (54, N'Czech Republic', 203, N'CZ', N'CZE', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (55, N'Germany', 276, N'DE', N'DEU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (56, N'Djibouti', 262, N'DJ', N'DJI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (57, N'Denmark', 208, N'DK', N'DNK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (58, N'Dominica', 212, N'DM', N'DMA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (59, N'Dominican Republic', 214, N'DO', N'DOM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (60, N'Algeria', 12, N'DZ', N'DZA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (61, N'Ecuador', 218, N'EC', N'ECU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (62, N'Estonia', 233, N'EE', N'EST', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (63, N'Egypt', 818, N'EG', N'EGY', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (64, N'Western Sahara', 732, N'EH', N'ESH', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (65, N'Eritrea', 232, N'ER', N'ERI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (66, N'Spain', 724, N'ES', N'ESP', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (67, N'Ethiopia', 231, N'ET', N'ETH', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (68, N'Finland', 246, N'FI', N'FIN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (69, N'Fiji', 242, N'FJ', N'FJI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (70, N'Falkland Islands (Malvinas)', 238, N'FK', N'FLK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (71, N'Micronesia, Federated States of', 583, N'FM', N'FSM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (72, N'Faroe Islands', 234, N'FO', N'FRO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (73, N'France', 250, N'FR', N'FRA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (74, N'Gabon', 266, N'GA', N'GAB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (75, N'United Kingdom', 826, N'GB', N'GBR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (76, N'Grenada', 308, N'GD', N'GRD', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (77, N'Georgia', 268, N'GE', N'GEO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (78, N'French Guiana', 254, N'GF', N'GUF', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (79, N'Ghana', 288, N'GH', N'GHA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (80, N'Gibraltar', 292, N'GI', N'GIB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (81, N'Greenland', 304, N'GL', N'GRL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (82, N'Gambia', 270, N'GM', N'GMB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (83, N'Guinea', 324, N'GN', N'GIN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (84, N'Guadeloupe', 312, N'GP', N'GLP', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (85, N'Equatorial Guinea', 226, N'GQ', N'GNQ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (86, N'Greece', 300, N'GR', N'GRC', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (87, N'South Georgia and the South Sandwich Islands', NULL, N'GS', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (88, N'Guatemala', 320, N'GT', N'GTM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (89, N'Guam', 316, N'GU', N'GUM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (90, N'Guinea-Bissau', 624, N'GW', N'GNB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (91, N'Guyana', 328, N'GY', N'GUY', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (92, N'Hong Kong', 344, N'HK', N'HKG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (93, N'Heard Island and Mcdonald Islands', NULL, N'HM', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (94, N'Honduras', 340, N'HN', N'HND', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (95, N'Croatia', 191, N'HR', N'HRV', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (96, N'Haiti', 332, N'HT', N'HTI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (97, N'Hungary', 348, N'HU', N'HUN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (98, N'Indonesia', 360, N'ID', N'IDN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (99, N'Ireland', 372, N'IE', N'IRL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (100, N'Israel', 376, N'IL', N'ISR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (101, N'India', 356, N'IN', N'IND', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (102, N'British Indian Ocean Territory', NULL, N'IO', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (103, N'Iraq', 368, N'IQ', N'IRQ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (104, N'Iran, Islamic Republic of', 364, N'IR', N'IRN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (105, N'Iceland', 352, N'IS', N'ISL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (106, N'Italy', 380, N'IT', N'ITA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (107, N'Jamaica', 388, N'JM', N'JAM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (108, N'Jordan', 400, N'JO', N'JOR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (109, N'Japan', 392, N'JP', N'JPN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (110, N'Kenya', 404, N'KE', N'KEN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (111, N'Kyrgyzstan', 417, N'KG', N'KGZ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (112, N'Cambodia', 116, N'KH', N'KHM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (113, N'Kiribati', 296, N'KI', N'KIR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (114, N'Comoros', 174, N'KM', N'COM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (115, N'Saint Kitts and Nevis', 659, N'KN', N'KNA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (116, N'Korea, Democratic People''s Republic of', 408, N'KP', N'PRK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (117, N'Korea, Republic of', 410, N'KR', N'KOR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (118, N'Kuwait', 414, N'KW', N'KWT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (119, N'Cayman Islands', 136, N'KY', N'CYM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (120, N'Kazakhstan', 398, N'KZ', N'KAZ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (121, N'Lao People''s Democratic Republic', 418, N'LA', N'LAO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (122, N'Lebanon', 422, N'LB', N'LBN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (123, N'Saint Lucia', 662, N'LC', N'LCA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (124, N'Liechtenstein', 438, N'LI', N'LIE', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (125, N'Sri Lanka', 144, N'LK', N'LKA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (126, N'Liberia', 430, N'LR', N'LBR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (127, N'Lesotho', 426, N'LS', N'LSO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (128, N'Lithuania', 440, N'LT', N'LTU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (129, N'Luxembourg', 442, N'LU', N'LUX', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (130, N'Latvia', 428, N'LV', N'LVA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (131, N'Libyan Arab Jamahiriya', 434, N'LY', N'LBY', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (132, N'Morocco', 504, N'MA', N'MAR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (133, N'Monaco', 492, N'MC', N'MCO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (134, N'Moldova, Republic of', 498, N'MD', N'MDA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (135, N'Madagascar', 450, N'MG', N'MDG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (136, N'Marshall Islands', 584, N'MH', N'MHL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (137, N'Macedonia, the Former Yugoslav Republic of', 807, N'MK', N'MKD', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (138, N'Mali', 466, N'ML', N'MLI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (139, N'Myanmar', 104, N'MM', N'MMR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (140, N'Mongolia', 496, N'MN', N'MNG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (141, N'Macao', 446, N'MO', N'MAC', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (142, N'Northern Mariana Islands', 580, N'MP', N'MNP', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (143, N'Martinique', 474, N'MQ', N'MTQ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (144, N'Mauritania', 478, N'MR', N'MRT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (145, N'Montserrat', 500, N'MS', N'MSR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (146, N'Malta', 470, N'MT', N'MLT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (147, N'Mauritius', 480, N'MU', N'MUS', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (148, N'Maldives', 462, N'MV', N'MDV', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (149, N'Malawi', 454, N'MW', N'MWI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (150, N'Mexico', 484, N'MX', N'MEX', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (151, N'Malaysia', 458, N'MY', N'MYS', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (152, N'Mozambique', 508, N'MZ', N'MOZ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (153, N'Namibia', 516, N'NA', N'NAM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (154, N'New Caledonia', 540, N'NC', N'NCL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (155, N'Niger', 562, N'NE', N'NER', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (156, N'Norfolk Island', 574, N'NF', N'NFK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (157, N'Nigeria', 566, N'NG', N'NGA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (158, N'Nicaragua', 558, N'NI', N'NIC', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (159, N'Netherlands', 528, N'NL', N'NLD', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (160, N'Norway', 578, N'NO', N'NOR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (161, N'Nepal', 524, N'NP', N'NPL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (162, N'Nauru', 520, N'NR', N'NRU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (163, N'Niue', 570, N'NU', N'NIU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (164, N'New Zealand', 554, N'NZ', N'NZL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (165, N'Oman', 512, N'OM', N'OMN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (166, N'Panama', 591, N'PA', N'PAN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (167, N'Peru', 604, N'PE', N'PER', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (168, N'French Polynesia', 258, N'PF', N'PYF', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (169, N'Papua New Guinea', 598, N'PG', N'PNG', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (170, N'Philippines', 608, N'PH', N'PHL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (171, N'Pakistan', 586, N'PK', N'PAK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (172, N'Poland', 616, N'PL', N'POL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (173, N'Saint Pierre and Miquelon', 666, N'PM', N'SPM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (174, N'Pitcairn', 612, N'PN', N'PCN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (175, N'Puerto Rico', 630, N'PR', N'PRI', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (176, N'Palestinian Territory, Occupied', NULL, N'PS', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (177, N'Portugal', 620, N'PT', N'PRT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (178, N'Palau', 585, N'PW', N'PLW', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (179, N'Paraguay', 600, N'PY', N'PRY', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (180, N'Qatar', 634, N'QA', N'QAT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (181, N'Reunion', 638, N'RE', N'REU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (182, N'Romania', 642, N'RO', N'ROM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (183, N'Russian Federation', 643, N'RU', N'RUS', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (184, N'Rwanda', 646, N'RW', N'RWA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (185, N'Saudi Arabia', 682, N'SA', N'SAU', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (186, N'Solomon Islands', 90, N'SB', N'SLB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (187, N'Seychelles', 690, N'SC', N'SYC', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (188, N'Sudan', 736, N'SD', N'SDN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (189, N'Sweden', 752, N'SE', N'SWE', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (190, N'Singapore', 702, N'SG', N'SGP', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (191, N'Saint Helena', 654, N'SH', N'SHN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (192, N'Slovenia', 705, N'SI', N'SVN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (193, N'Svalbard and Jan Mayen', 744, N'SJ', N'SJM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (194, N'Slovakia', 703, N'SK', N'SVK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (195, N'Sierra Leone', 694, N'SL', N'SLE', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (196, N'San Marino', 674, N'SM', N'SMR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (197, N'Senegal', 686, N'SN', N'SEN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (198, N'Somalia', 706, N'SO', N'SOM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (199, N'Suriname', 740, N'SR', N'SUR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (200, N'Sao Tome and Principe', 678, N'ST', N'STP', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (201, N'El Salvador', 222, N'SV', N'SLV', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (202, N'Syrian Arab Republic', 760, N'SY', N'SYR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (203, N'Swaziland', 748, N'SZ', N'SWZ', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (204, N'Turks and Caicos Islands', 796, N'TC', N'TCA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (205, N'Chad', 148, N'TD', N'TCD', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (206, N'French Southern Territories', NULL, N'TF', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (207, N'Togo', 768, N'TG', N'TGO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (208, N'Thailand', 764, N'TH', N'THA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (209, N'Tajikistan', 762, N'TJ', N'TJK', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (210, N'Tokelau', 772, N'TK', N'TKL', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (211, N'Timor-Leste', NULL, N'TL', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (212, N'Turkmenistan', 795, N'TM', N'TKM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (213, N'Tunisia', 788, N'TN', N'TUN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (214, N'Tonga', 776, N'TO', N'TON', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (215, N'Turkey', 792, N'TR', N'TUR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (216, N'Trinidad and Tobago', 780, N'TT', N'TTO', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (217, N'Tuvalu', 798, N'TV', N'TUV', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (218, N'Taiwan, Province of China', 158, N'TW', N'TWN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (219, N'Tanzania, United Republic of', 834, N'TZ', N'TZA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (220, N'Ukraine', 804, N'UA', N'UKR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (221, N'Uganda', 800, N'UG', N'UGA', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (222, N'United States Minor Outlying Islands', NULL, N'UM', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (223, N'United States', 840, N'US', N'USA', 1)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (224, N'Uruguay', 858, N'UY', N'URY', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (225, N'Uzbekistan', 860, N'UZ', N'UZB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (226, N'Holy See (Vatican City State)', 336, N'VA', N'VAT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (227, N'Saint Vincent and the Grenadines', 670, N'VC', N'VCT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (228, N'Venezuela', 862, N'VE', N'VEN', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (229, N'Virgin Islands, British', 92, N'VG', N'VGB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (230, N'Virgin Islands, U.s.', 850, N'VI', N'VIR', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (231, N'Viet Nam', 704, N'VN', N'VNM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (232, N'Vanuatu', 548, N'VU', N'VUT', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (233, N'Wallis and Futuna', 876, N'WF', N'WLF', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (234, N'Samoa', 882, N'WS', N'WSM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (235, N'Yemen', 887, N'YE', N'YEM', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (236, N'Mayotte', NULL, N'YT', NULL, 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (237, N'South Africa', 710, N'ZA', N'ZAF', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (238, N'Zambia', 894, N'ZM', N'ZMB', 1000)
INSERT [dbo].[Country] ([Id], [Name], [NumericCode], [Alpha2], [Alpha3], [Ordinal]) VALUES (239, N'Zimbabwe', 716, N'ZW', N'ZWE', 1000)";


        private const string StateInsertSql = @"INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (1, 223, N'Alaska', N'AK')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (2, 223, N'Alabama', N'AL')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (3, 223, N'American Samoa', N'AS')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (4, 223, N'Arizona', N'AZ')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (5, 223, N'Arkansas', N'AR')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (6, 223, N'California', N'CA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (7, 223, N'Colorado', N'CO')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (8, 223, N'Connecticut', N'CT')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (9, 223, N'Delaware', N'DE')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (10, 223, N'District of Columbia', N'DC')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (11, 223, N'Federated States of Micronesia', N'FM')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (12, 223, N'Florida', N'FL')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (13, 223, N'Georgia', N'GA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (14, 223, N'Guam', N'GU')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (15, 223, N'Hawaii', N'HI')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (16, 223, N'Idaho', N'ID')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (17, 223, N'Illinois', N'IL')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (18, 223, N'Indiana', N'IN')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (19, 223, N'Iowa', N'IA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (20, 223, N'Kansas', N'KS')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (21, 223, N'Kentucky', N'KY')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (22, 223, N'Louisiana', N'LA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (23, 223, N'Maine', N'ME')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (24, 223, N'Marshall Islands', N'MH')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (25, 223, N'Maryland', N'MD')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (26, 223, N'Massachusetts', N'MA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (27, 223, N'Michigan', N'MI')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (28, 223, N'Minnesota', N'MN')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (29, 223, N'Mississippi', N'MS')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (30, 223, N'Missouri', N'MO')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (31, 223, N'Montana', N'MT')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (32, 223, N'Nebraska', N'NE')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (33, 223, N'Nevada', N'NV')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (34, 223, N'New Hampshire', N'NH')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (35, 223, N'New Jersey', N'NJ')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (36, 223, N'New Mexico', N'NM')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (37, 223, N'New York', N'NY')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (38, 223, N'North Carolina', N'NC')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (39, 223, N'North Dakota', N'ND')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (40, 223, N'Northern Mariana Islands', N'MP')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (41, 223, N'Ohio', N'OH')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (42, 223, N'Oklahoma', N'OK')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (43, 223, N'Oregon', N'OR')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (44, 223, N'Palau', N'PW')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (45, 223, N'Pennsylvania', N'PA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (46, 223, N'Puerto Rico', N'PR')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (47, 223, N'Rhode Island', N'RI')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (48, 223, N'South Carolina', N'SC')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (49, 223, N'South Dakota', N'SD')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (50, 223, N'Tennessee', N'TN')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (51, 223, N'Texas', N'TX')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (52, 223, N'Utah', N'UT')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (53, 223, N'Vermont', N'VT')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (54, 223, N'Virgin Islands', N'VI')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (55, 223, N'Virginia', N'VA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (56, 223, N'Washington', N'WA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (57, 223, N'West Virginia', N'WV')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (58, 223, N'Wisconsin', N'WI')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (59, 223, N'Wyoming', N'WY')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (60, 223, N'Armed Forces Africa', N'AE')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (61, 223, N'Armed Forces Americas (except Canada)', N'AA')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (62, 223, N'Armed Forces Canada', N'AE')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (63, 223, N'Armed Forces Europe', N'AE')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (64, 223, N'Armed Forces Middle East', N'AE')
INSERT [dbo].[State] ([Id], [CountryId], [Name], [Code]) VALUES (65, 223, N'Armed Forces Pacific', N'AP')";
    }
}
